export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_LIST_BY_SELL_REQUEST = 'PRODUCT_LIST_BY_SELL_REQUEST'
export const PRODUCT_LIST_BY_SELL_SUCCESS = 'PRODUCT_LIST_BY_SELL_SUCCESS'
export const PRODUCT_LIST_BY_SELL_FAIL = 'PRODUCT_LIST_BY_SELL_FAIL'

export const PRODUCT_LIST_BY_ARRIVAL_REQUEST = 'PRODUCT_LIST_BY_ARRIVAL_REQUEST'
export const PRODUCT_LIST_BY_ARRIVAL_SUCCESS = 'PRODUCT_LIST_BY_ARRIVAL_SUCCESS'
export const PRODUCT_LIST_BY_ARRIVAL_FAIL = 'PRODUCT_LIST_BY_ARRIVAL_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'